import Block from '@/components/block'
import Head from 'next/head'
import Blocks from '@/components/Blocks'
import Image from 'next/image'
import blockFile from '../public/blockFile.json'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Block />
      <Blocks blockFile={blockFile} />
      
    </>
  )
}
